"""
Machine Learning Model Adapter and Decision Engine.
Supports dynamic loading of trained joblib/pickle scikit-learn models,
probabilistic inference across 5 recovery pathways, safety guardrail enforcement,
and baseline probabilistic fallback when no trained model file is present.
"""

import os
import json
import logging
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, Any, List, Tuple, Optional

from app.schemas.assessment import (
    WasteInput,
    AssessmentResult,
    DecisionStep,
    HierarchyEvaluation,
    SustainabilityAssessment
)
from app.ml.config import (
    DEFAULT_MODEL_FILE,
    METADATA_FILE,
    TARGET_CLASSES,
    ALL_FEATURE_COLUMNS
)
from app.ml.preprocessor import extract_features_from_input, features_to_input_dataframe

logger = logging.getLogger("ml_adapter")

DISCLAIMER_TEXT = (
    "This decision-support recommendation is generated by a Machine Learning model "
    "operating under civil and environmental engineering safety constraints. "
    "It does not replace certified laboratory testing or regulatory compliance requirements."
)

class BaselineProbabilisticModel:
    """
    Explainable probabilistic baseline predictor used when the user has not yet
    placed a trained .joblib model in saved_models/.
    Computes soft class probabilities across the 5 target recovery pathways.
    """
    def __init__(self):
        self.classes_ = TARGET_CLASSES

    def predict_proba_from_features(self, feat: Dict[str, Any]) -> Dict[str, float]:
        cond_score = feat.get("condition_score", 2.0) # 0 to 4
        contam_score = feat.get("contamination_score", 0.0) # 0 to 4
        has_cracks = feat.get("has_cracks", 0.0)
        struct_comp = feat.get("structural_compromised", 0.0)
        has_rust = feat.get("has_rust", 0.0)
        has_rot = feat.get("has_rot", 0.0)
        broken_pct = feat.get("broken_percentage", 0.0)
        is_hazard = feat.get("contamination") == "Hazardous" or feat.get("has_hazardous_coating", 0.0) == 1.0

        scores = {
            "REUSE": 0.05,
            "REPAIR": 0.05,
            "RECYCLE": 0.10,
            "RECOVER": 0.05,
            "DISPOSAL / SPECIALIZED HANDLING": 0.02
        }

        if is_hazard:
            scores["DISPOSAL / SPECIALIZED HANDLING"] += 0.90
            scores["REUSE"] = 0.0
            scores["REPAIR"] = 0.0
            scores["RECYCLE"] = 0.02
            scores["RECOVER"] = 0.03
        else:
            # Reuse affinity: high condition, zero contamination, intact geometry
            if cond_score >= 3.0 and contam_score == 0 and struct_comp == 0 and has_cracks == 0 and broken_pct < 10:
                scores["REUSE"] += 0.75
                scores["REPAIR"] += 0.10
                scores["RECYCLE"] += 0.05
            elif cond_score >= 2.0 and (has_rust or struct_comp or (10 <= broken_pct <= 30)):
                # Repair / reconditioning affinity
                scores["REPAIR"] += 0.55
                scores["RECYCLE"] += 0.30
                scores["REUSE"] += 0.10
            elif cond_score <= 2.0 or has_cracks or broken_pct > 30 or struct_comp:
                # Recycling affinity: damaged/broken but clean material
                scores["RECYCLE"] += 0.70
                scores["RECOVER"] += 0.15
                scores["REUSE"] += 0.02
            else:
                scores["RECYCLE"] += 0.50
                scores["RECOVER"] += 0.30

            # High contamination reduces recycling and pushes to disposal or recovery
            if contam_score >= 3.0:
                scores["DISPOSAL / SPECIALIZED HANDLING"] += 0.60
                scores["RECOVER"] += 0.25
                scores["REUSE"] = 0.01

        # Normalize to probability distribution (sums to 1.0)
        total = sum(scores.values())
        return {k: round(v / total, 4) for k, v in scores.items()}

# Global model cache
_LOADED_MODEL = None
_LOADED_METADATA = None

def get_loaded_model():
    """
    Attempts to load user's trained model from DEFAULT_MODEL_FILE.
    Returns (model, metadata_dict, is_trained_model_loaded).
    """
    global _LOADED_MODEL, _LOADED_METADATA

    if DEFAULT_MODEL_FILE.exists():
        try:
            import joblib
            if _LOADED_MODEL is None:
                _LOADED_MODEL = joblib.load(DEFAULT_MODEL_FILE)
                logger.info(f"Loaded trained ML model from {DEFAULT_MODEL_FILE}")
            
            metadata = {}
            if METADATA_FILE.exists():
                try:
                    with open(METADATA_FILE, "r", encoding="utf-8") as f:
                        metadata = json.load(f)
                except Exception:
                    pass
            
            return _LOADED_MODEL, metadata, True
        except Exception as e:
            logger.warning(f"Failed to load model file at {DEFAULT_MODEL_FILE}: {e}")

    return BaselineProbabilisticModel(), {}, False

def get_model_status() -> Dict[str, Any]:
    """
    Returns diagnostic information about the ML model status for API & UI.
    """
    _, meta, is_trained = get_loaded_model()
    return {
        "model_file_exists": DEFAULT_MODEL_FILE.exists(),
        "model_file_path": str(DEFAULT_MODEL_FILE),
        "is_user_trained_model_loaded": is_trained,
        "model_engine": "Trained Scikit-Learn Model" if is_trained else "Probabilistic Baseline Adapter (Awaiting User Model)",
        "model_version": meta.get("version", "v1.0.0-custom" if is_trained else "v0.1-placeholder"),
        "target_classes": TARGET_CLASSES,
        "required_feature_columns": ALL_FEATURE_COLUMNS,
        "instructions": (
            "To deploy your trained model: train using `backend/app/ml/train_template.py` "
            "or save any scikit-learn Pipeline with .predict() and .predict_proba() "
            "to `backend/app/ml/saved_models/waste_recovery_model.joblib`."
        )
    }

def evaluate_waste_ml(waste_input: WasteInput) -> AssessmentResult:
    """
    Executes the Machine Learning Assessment Pipeline:
    1. Feature extraction & tabular transformation
    2. Model inference (user trained model or probabilistic baseline)
    3. Multi-class probability extraction & confidence calculation
    4. Environmental & civil engineering safety guardrail verification
    5. Circular waste hierarchy alignment
    6. Traceable decision steps, qualitative sustainability, applications & alternatives
    """
    material = waste_input.material
    condition = waste_input.condition
    contamination = waste_input.contamination
    quantity = waste_input.quantity
    unit = waste_input.unit
    chars = waste_input.additional_characteristics or {}

    # Step 1: Preprocess input into feature vector
    features = extract_features_from_input(waste_input)
    decision_steps: List[DecisionStep] = []

    decision_steps.append(DecisionStep(
        stage="PREPROCESSING",
        title="Feature Extraction & Preprocessing",
        description=f"Constructed {len(features)} tabular features (Material: {material}, Quantity: {quantity:g} {unit}, Degradation Score: {features['condition_score']}/4, Contamination Score: {features['contamination_score']}/4).",
        status="completed",
        details=features
    ))

    # Safety constraint assessment
    is_hazardous = contamination in ["High", "Hazardous"] or features.get("has_hazardous_coating", 0) == 1.0
    professional_req = is_hazardous or condition == "Severely Damaged" or features.get("structural_compromised", 0) == 1.0

    decision_steps.append(DecisionStep(
        stage="SAFETY_GUARDRAIL",
        title="Safety & Regulatory Guardrail Verification",
        description="Hazardous contamination or structural compromise detected. Enforcing specialized safety protocols." if is_hazardous
                    else "Passed safety screening; safe for circular recovery pathways.",
        status="completed",
        details={"is_hazardous": is_hazardous, "professional_assessment_required": professional_req}
    ))

    # Step 2: ML Inference
    model, meta, is_trained = get_loaded_model()
    model_name = meta.get("model_name", type(model).__name__)
    model_version = meta.get("version", "v1.0-trained" if is_trained else "v0.1-placeholder")
    inference_source = "USER_TRAINED_ML_MODEL" if is_trained else "BASELINE_PROBABILISTIC_ENGINE"

    probabilities: Dict[str, float] = {}

    if is_trained:
        try:
            import pandas as pd
            df_input = pd.DataFrame([features], columns=ALL_FEATURE_COLUMNS)
            
            # Predict probabilities
            if hasattr(model, "predict_proba"):
                raw_probs = model.predict_proba(df_input)[0]
                classes = list(getattr(model, "classes_", TARGET_CLASSES))
                for cls_name, p in zip(classes, raw_probs):
                    cls_str = str(cls_name).strip()
                    probabilities[cls_str] = round(float(p), 4)
            elif hasattr(model, "predict"):
                pred_label = str(model.predict(df_input)[0])
                for cls in TARGET_CLASSES:
                    probabilities[cls] = 0.95 if cls == pred_label else 0.0125
        except Exception as err:
            logger.error(f"Inference error with trained model: {err}. Falling back to baseline.")
            fallback = BaselineProbabilisticModel()
            probabilities = fallback.predict_proba_from_features(features)
            inference_source = "FALLBACK_AFTER_INFERENCE_ERROR"
    else:
        # User has not added model yet (LEAVE ML PLACE EMPTY requirement)
        baseline = BaselineProbabilisticModel()
        probabilities = baseline.predict_proba_from_features(features)

    # Ensure all 5 target classes exist in probabilities dictionary
    for cls in TARGET_CLASSES:
        if cls not in probabilities:
            probabilities[cls] = 0.0

    # Determine top predicted pathway from ML probabilities
    predicted_pathway = max(probabilities.items(), key=lambda x: x[1])[0]
    confidence_score = float(probabilities[predicted_pathway])

    # Enforce Safety Guardrail Override if hazardous
    if is_hazardous:
        predicted_pathway = "DISPOSAL / SPECIALIZED HANDLING"
        confidence_score = max(confidence_score, 0.985)
        probabilities["DISPOSAL / SPECIALIZED HANDLING"] = 0.985
        inference_source += " (Safety Override Enforced)"

    confidence_pct = round(confidence_score * 100, 1)

    decision_steps.append(DecisionStep(
        stage="ML_INFERENCE",
        title="Machine Learning Probabilistic Classification",
        description=f"Model classified optimal recovery pathway as {predicted_pathway} with {confidence_pct}% confidence.",
        status="completed",
        details={
            "model_name": model_name,
            "version": model_version,
            "confidence_score": confidence_score,
            "prediction_probabilities": probabilities,
            "inference_source": inference_source
        }
    ))

    # Step 3: Hierarchy Evaluation Matrix
    hierarchy_eval: List[HierarchyEvaluation] = []
    p_tier = predicted_pathway.upper()

    hierarchy_tiers = [
        ("1", "REUSE", "Highest value circular pathway: whole component salvage & direct reuse."),
        ("2", "REPAIR", "Component refurbishment: minor reconditioning, recutting, or cleaning."),
        ("3", "RECYCLE", "Reprocessing: mechanical sorting/crushing into secondary aggregate/feedstock."),
        ("4", "RECOVER", "Energy/Thermal recovery or bulk material recovery facility separation."),
        ("5", "DISPOSE / SPECIALIZED HANDLING", "Regulated environmental containment or hazardous waste protocol.")
    ]

    for tier_num, tier_name, tier_desc in hierarchy_tiers:
        is_selected = tier_name in p_tier or (tier_num == "5" and "DISPOS" in p_tier)
        p_val = probabilities.get(tier_name, 0.0)
        
        if is_selected:
            h_status = "Selected (Optimal Pathway)"
            reason_text = f"Selected by ML Classifier with {round(p_val * 100, 1)}% probability. {tier_desc}"
        else:
            h_status = f"{round(p_val * 100, 1)}% Probability"
            reason_text = f"Alternative recovery option. {tier_desc}"

        hierarchy_eval.append(HierarchyEvaluation(
            tier=tier_num,
            name=tier_name,
            selected=is_selected,
            status=h_status,
            reason=reason_text
        ))

    decision_steps.append(DecisionStep(
        stage="HIERARCHY_ALIGNMENT",
        title="Circular Waste Hierarchy Alignment",
        description=f"Mapped prediction to circular priority hierarchy: {predicted_pathway}.",
        status="completed",
        details={"hierarchy": [h.model_dump() for h in hierarchy_eval]}
    ))

    # Step 4: Reasoning statement
    if "REUSE" in p_tier:
        reason = f"ML model detected high geometric integrity and low degradation for {material}, recommending direct salvage and architectural reuse."
    elif "REPAIR" in p_tier:
        reason = f"ML model identified localized superficial damage on {material} that can be refurbished or reconditioned for circular reuse."
    elif "RECYCLE" in p_tier:
        reason = f"Direct reuse is unsuitable due to material condition, while clean {material.lower()} remains suitable for processing into recycled aggregate and secondary feedstock."
    elif "RECOVER" in p_tier:
        reason = f"ML model recommended energy or thermal recovery for {material.lower()} as the optimal feasible recovery mechanism."
    else:
        reason = f"Hazardous contamination or severe structural degradation mandates regulated specialized containment and professional handling."

    # Applications and alternatives
    applications = _generate_applications(material, predicted_pathway)
    alternatives = _generate_alternatives(predicted_pathway)

    # Qualitative sustainability metrics
    sustainability = _generate_sustainability(predicted_pathway)

    # Conditions / Top contributing features
    conditions_satisfied = [
        f"Material = {material}",
        f"Condition = {condition} (Score: {features['condition_score']}/4)",
        f"Contamination = {contamination} (Score: {features['contamination_score']}/4)",
        f"ML Model Confidence = {confidence_pct}%",
        f"Inference Engine = {model_name} ({inference_source})"
    ]

    for k, v in chars.items():
        if v not in [None, ""]:
            conditions_satisfied.append(f"{k.replace('_', ' ').title()} = {v}")

    return AssessmentResult(
        timestamp=datetime.now(timezone.utc),
        input_summary=waste_input,
        recommended_pathway=predicted_pathway,
        rule_match_strength=f"ML Confidence: {confidence_pct}%",
        matched_rule=f"ML-{model_name}",
        reason=reason,
        conditions_satisfied=conditions_satisfied,
        potential_applications=applications,
        alternative_options=alternatives,
        decision_steps=decision_steps,
        hierarchy_evaluation=hierarchy_eval,
        sustainability=sustainability,
        safety_disclaimer=DISCLAIMER_TEXT,
        professional_assessment_required=professional_req,
        confidence_score=confidence_score,
        prediction_probabilities=probabilities,
        model_name=model_name,
        model_version=model_version,
        inference_source=inference_source
    )

def _generate_applications(material: str, pathway: str) -> List[str]:
    m = material.lower()
    p = pathway.upper()

    if "REUSE" in p:
        if "concrete" in m:
            return ["Direct structural salvage", "Modular retaining walls", "Paving slabs"]
        if "brick" in m:
            return ["Architectural heritage reuse", "Facing masonry", "Interior partition walls"]
        if "steel" in m:
            return ["Direct structural member reuse", "Secondary framing", "Truss reinforcement"]
        if "wood" in m:
            return ["Architectural timber reclamation", "Secondary carpentry", "Interior furniture"]
        return ["Direct component salvage", "Secondary construction applications"]

    if "REPAIR" in p:
        if "steel" in m:
            return ["Structural re-welding & re-straightening", "Rust descaling & recoating"]
        if "wood" in m:
            return ["Trimming & re-milling damaged ends", "Fungicidal remediation & re-planing"]
        return ["Reconditioning and cleaning", "Surface refinishing for secondary installation"]

    if "RECYCLE" in p:
        if "concrete" in m:
            return ["Crushed recycled aggregate (RCA)", "Road base sub-base course", "Engineered fill"]
        if "brick" in m:
            return ["Crushed brick aggregate for green roofs", "Decorative landscaping aggregate", "Sub-base binder"]
        if "steel" in m:
            return ["Electric Arc Furnace (EAF) scrap charge", "New reinforcement rebar production"]
        if "wood" in m:
            return ["Particleboard and OSB manufacturing", "Engineered wood pulp feedstock"]
        return ["Secondary raw material feedstock", "Industrial mechanical recycling"]

    if "RECOVER" in p:
        return ["Industrial biomass co-firing", "Material Recovery Facility (MRF) fiber sorting", "Waste-to-energy incineration"]

    return ["Certified hazardous containment facility", "Regulated monofill cell", "Controlled specialized treatment"]

def _generate_alternatives(pathway: str) -> List[str]:
    p = pathway.upper()
    if "REUSE" in p:
        return ["Mechanical recycling into secondary feedstock", "Controlled downcycling for non-critical uses"]
    if "REPAIR" in p:
        return ["Downcycling into secondary components", "Direct recycling if repair labor exceeds value"]
    if "RECYCLE" in p:
        return ["Controlled reuse for suitable non-structural applications", "Controlled sub-base backfill"]
    if "RECOVER" in p:
        return ["Downcycling into landscaping mulch", "Secondary sorting if clean fraction can be segregated"]
    return ["Specialized chemical stabilization prior to landfill", "Professional laboratory toxicity leaching analysis"]

def _generate_sustainability(pathway: str) -> SustainabilityAssessment:
    p = pathway.upper()
    if "REUSE" in p:
        return SustainabilityAssessment(
            landfill_avoidance="VERY HIGH (99%+ Diverted)",
            material_recovery="MAXIMUM (100% Whole Component)",
            resource_conservation="VERY HIGH (Eliminates Virgin Material Production)",
            circularity_potential="VERY HIGH (Closed-Loop Preservation)",
            assessment_type="Machine Learning Qualitative Sustainability Index",
            note="Highest possible circular economy pathway: retains structural embodied carbon."
        )
    elif "REPAIR" in p:
        return SustainabilityAssessment(
            landfill_avoidance="HIGH (90%+ Diverted)",
            material_recovery="HIGH (95%+ Retained)",
            resource_conservation="HIGH (Minimizes Manufacturing Energy)",
            circularity_potential="HIGH (Refurbishment Loop)",
            assessment_type="Machine Learning Qualitative Sustainability Index",
            note="Restores utility with minimal secondary energy input."
        )
    elif "RECYCLE" in p:
        return SustainabilityAssessment(
            landfill_avoidance="HIGH (85%+ Diverted)",
            material_recovery="HIGH (Processed Aggregate / Secondary Feedstock)",
            resource_conservation="HIGH (Offsets Virgin Quarrying and Smelting)",
            circularity_potential="HIGH (Secondary Loop Reprocessing)",
            assessment_type="Machine Learning Qualitative Sustainability Index",
            note="Conserves landfill space and displaces virgin raw material extraction."
        )
    elif "RECOVER" in p:
        return SustainabilityAssessment(
            landfill_avoidance="MODERATE (50-70% Diverted)",
            material_recovery="MODERATE (Energy / Downcycled Biomass)",
            resource_conservation="MODERATE (Displaces Fossil Energy / Raw Fiber)",
            circularity_potential="MODERATE (Open-Loop Recovery)",
            assessment_type="Machine Learning Qualitative Sustainability Index",
            note="Captures thermal or residual value where physical recycling is unviable."
        )
    else:
        return SustainabilityAssessment(
            landfill_avoidance="NONE (Regulated Containment)",
            material_recovery="LOW (Zero Safe Material Recovery)",
            resource_conservation="NONE (Containment Protocol Mandated)",
            circularity_potential="LINEAR (Containment / Disposal)",
            assessment_type="Machine Learning Qualitative Sustainability Index",
            note="Ensures environmental protection and regulatory compliance for hazardous/degraded waste."
        )
